export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const SET_CURREN_USER = "SET_CURREN_USER";

export const LOGOUT = "LOGOUT";

//Projects

export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const RETRIEVE_USER_PROJECTS = "RETRIEVE_USER_PROJECTS";
export const RETRIEVE_USER_PROJECTS_FAIL = "RETRIEVE_USER_PROJECTS_FAIL";

export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const RETRIEVE_PROJECTS_FAIL = "RETRIEVE_PROJECTS_FAIL";

export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";

//tasks

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_FAIL = "GET_TASKS_FAIL";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const SET_CURRENT_TASK = "SET_CURRENT_TASK";

//others
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
